sudo: required
services: 
  - docker
before_install:
  - docker build -t praveen/docker-react  -f Dockerfile.dev .
script: 
   - docker run -e CI=true praveen/docker-react echo "Hello World"
 
deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker-react"
   env: "Dockerreact-env"
   bucket_name: "elasticbeanstalk-us-east-1-685754223027"
   bucket_path: "docker-react"
   on:
     branch: main
   access_key_id: 
     secure: "$ACCESS_KEY_ID"
   secret_access_key:
      secure: "$AWS_SECRET"    

  
